src/main/java/org/yidu/novel/entity/TArticle.java
package org.yidu.novel.entity;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.struts2.ServletActionContext;
import org.yidu.novel.action.ArticleListAction;
import org.yidu.novel.action.ChapterListAction;
import org.yidu.novel.action.DownloadAction;
import org.yidu.novel.action.InfoAction;
import org.yidu.novel.action.ReaderAction;
import org.yidu.novel.action.ReviewListAction;
import org.yidu.novel.action.user.BookcaseAction;
import org.yidu.novel.action.user.SubscribeAction;
import org.yidu.novel.action.user.VoteAction;
import org.yidu.novel.cache.SingleBookManager;
import org.yidu.novel.constant.YiDuConfig;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.dto.TagDTO;
import org.yidu.novel.entity.base.BaseTArticle;
import org.yidu.novel.utils.Utils;

public class TArticle extends BaseTArticle {
    private static final long serialVersionUID = 1L;

    /* [CONSTRUCTOR MARKER BEGIN] */
    public TArticle() {
        super();
    }

    /**
     * Constructor for primary key
     */
    public TArticle(int articleno) {
        super(articleno);
    }

    /* [CONSTRUCTOR MARKER END] */

    public Boolean getFullflag() {
        return isFullflag();
    }

    public Boolean getFirstflag() {
        return isFirstflag();
    }

    public Boolean getAuthorflag() {
        return isAuthorflag();
    }

    public Boolean getDeleteflag() {
        return isDeleteflag();
    }

    public Boolean getUsecustomizeinfotitle() {
        return isUsecustomizeinfotitle();
    }

    public Boolean getUsecustomizelisttitle() {
        return isUsecustomizelisttitle();
    }

    /**
     * 获取HTML格式的小说简介信息
     * 
     * @return HTML格式的小说简介信息
     */
    public String getIntroForHtml() {
        if (getIntro() != null) {
            // 替换换行和空格
            String html = StringEscapeUtils.escapeHtml4(getIntro());
            return html.replaceAll("\r\n", "<br/>").replaceAll("\n", "<br/>").replaceAll("\\s", "&nbsp;");
        }
        return null;
    }

    /**
     * 获得小说简介的缩略
     * 
     * @return 小说简介的缩略
     */
    public String getIntroOmit() {
        if (getIntro() != null && getIntro().length() > 60) {
            return getIntro().substring(0, 60) + "...";
        }
        return getIntro();
    }

    /**
     * 获得子目录 <br>
     * 默认是小说号/1000
     * 
     * @return 子目录
     */
    public Integer getSubdir() {
        return getArticleno() / YiDuConstants.SUB_DIR_ARTICLES;
    }

    /**
     * 获得最新章节名字的缩略
     * 
     * @return 最新章节名字的缩略
     */
    public String getLastchapterOmit() {
        if (getLastchapter() != null && getLastchapter().length() > 10) {
            return getLastchapter().substring(0, 10);
        }
        return getLastchapter();
    }

    /**
     * 获得最后更新时间
     * 
     * @return 最后更新时间
     */
    public String getLastupdateMin() {
        SimpleDateFormat sdf1 = new SimpleDateFormat("HH:mm:ss");
        return sdf1.format(getLastupdate());
    }

    /**
     * 获得小说类别名字
     * 
     * @return 小说类别名字
     */
    @Deprecated
    public String getCategoryStr() {
        String[] categoryArr = new String[] { "玄幻魔法", "武侠修真", "都市言情", "历史军事", "侦探推理", "网游动漫", "科幻小说", "恐怖灵异", "散文诗词",
                "其他类型" };
        return categoryArr[getCategory() - 1];
    }

    /**
     * 获得图片URL
     * 
     * @return 图片URL
     */
    public String getImgUrl() {
        String fileName = "";
        if (getImgflag() == null) {
            fileName = "nocover.jpg";
        } else {
            switch (getImgflag()) {
            case 1:
                fileName = getArticleno() + "s.jpg";
                break;
            case 2:
                fileName = getArticleno() + "s.gif";
                break;
            case 3:
                fileName = getArticleno() + "s.png";
                break;
            case 10:
                fileName = getArticleno() + "l.jpg";
                break;
            default:
                fileName = "nocover.jpg";
                break;
            }
        }
        String imgUrl = YiDuConstants.yiduConf.getString(YiDuConfig.RELATIVE_IAMGE_PATH) + "/";
        if (StringUtils.equals("nocover.jpg", fileName)) {
            imgUrl = imgUrl + fileName;
        } else {
            if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_CLEAN_IMAGE_URL, false)) {
                imgUrl = imgUrl + getArticleno() / YiDuConstants.SUB_DIR_ARTICLES + "-" + getArticleno() + "-"
                        + Utils.convert2MD5(imgUrl + fileName) + fileName;
            } else {
                imgUrl = imgUrl + getArticleno() / YiDuConstants.SUB_DIR_ARTICLES + "/" + getArticleno() + "/"
                        + fileName;
            }
        }
        return imgUrl;
    }

    /**
     * 获取小说介绍页URL
     * 
     * @return 小说介绍页URL
     */
    public String getUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(InfoAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(InfoAction.URL + "?pinyin=" + getPinyin());
        }
        return url;
    }

    /**
     * 获取作者列表URL
     * 
     * @return 作者列表URL
     */
    public String getAuthorUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ArticleListAction.URL + "?author=" + getAuthor());
    }

    /**
     * 获取分类列表URL
     * 
     * @return 分类列表URL
     */
    public String getCategoryListUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ArticleListAction.URL + "?category=" + getCategory());
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getLastChapterUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno()
                + "&chapterno=" + getLastchapterno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ReaderAction.URL + "?pinyin=" + getPinyin() + "&chapterno=" + getLastchapterno());
        }
        return url;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getThumbnailLastChapterUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ReaderAction.URL + "?chapterno=" + getLastchapterno());
    }

    /**
     * 获取加入书签URL
     * 
     * @return 加入书签URL
     */
    public String getAddBookcaseUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(BookcaseAction.URL + "!add?articleno=" + getArticleno());
    }

    /**
     * 获取推荐小说URL
     * 
     * @return 推荐小说URL
     */
    public String getAddVoteUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(VoteAction.URL + "?articleno=" + getArticleno());
    }

    /**
     * 获取下载小说URL
     * 
     * @return 下载小说URL
     */
    public String getDownloadUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(DownloadAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());
    }

    /**
     * 获取小说评价URL
     * 
     * @return 小说评价URL
     */
    public String getReviewUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ReviewListAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());
    }

    /**
     * 获取章节列表URL
     * 
     * @return 分类列表URL
     */
    public String getChapterListUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ChapterListAction.URL + "?subdir=" + getSubdir() + "&articleno="
                + getArticleno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ChapterListAction.URL + "?pinyin=" + getPinyin());
        }
        return url;
    }

    /**
     * 获取订阅URL
     * 
     * @return 订阅URL
     */
    public String getSubscribeUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(SubscribeAction.URL + "!add?articleno=" + getArticleno());
    }

    /**
     * 获取小说介绍页拼音形式的URL
     * 
     * @return 小说介绍页拼音形式的URL
     */
    public String getSingleBookUrl() {
        String pinyin = SingleBookManager.getPinYinHeadChar(getArticleno());
        if (StringUtils.isNotBlank(pinyin)) {
            return "http://" + pinyin + "." + YiDuConstants.yiduConf.getString(YiDuConfig.ROOT_DOMAIN);
        } else {
            return YiDuConstants.yiduConf.getString(YiDuConfig.ROOT_DOMAIN);
        }
    }

    /**
     * 获取小说tag的URL
     * 
     * @return 小说介绍页拼音形式的URL
     */
    public List<TagDTO> getTagList() {
        List<String> tags = Utils.getKeyWords(getArticlename());
        List<TagDTO> tagList = new ArrayList<TagDTO>();
        HttpServletResponse response = ServletActionContext.getResponse();
        for (String tag : tags) {
            TagDTO tagdto = new TagDTO();
            tagdto.setTag(tag);

src/main/java/org/yidu/novel/action/ArticleListAction.java
package org.yidu.novel.action;

import java.util.ArrayList;
import java.util.List;

import org.apache.struts2.convention.annotation.Action;
import org.springframework.beans.BeanUtils;
import org.yidu.novel.action.base.AbstractPublicListBaseAction;
import org.yidu.novel.bean.ArticleSearchBean;
import org.yidu.novel.cache.ArticleCountManager;
import org.yidu.novel.cache.CacheManager;
import org.yidu.novel.constant.YiDuConfig;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.entity.TArticle;
import org.yidu.novel.utils.Utils;

/**
 * 
 * <p>
 * 小说列表Action
 * </p>
 * Copyright(c) 2013 YiDu-Novel. All rights reserved.
 * 
 * @version 1.0.0
 * @author shinpa.you
 */
@Action(value = "articleList")
public class ArticleListAction extends AbstractPublicListBaseAction {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = -4215796997609788238L;

    /**
     * 功能名称。
     */
    public static final String NAME = "articleList";

    /**
     * 访问URL。
     */
    public static final String URL = NAMESPACE + "/" + NAME;

    /**
     * 小说种类
     */
    private Integer category;

    /**
     * 页号
     */
    private int page;

    /**
     * 作者
     */
    private String author;

    /**
     * 完本标志
     */
    private Boolean fullflag;
    /**
     * 标签
     */
    private String tag;

    /**
     * 小说列表
     */
    private List<TArticle> articleList = new ArrayList<TArticle>();

    /**
     * 获取category
     * 
     * @return category
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * 
     * 设置category
     * 
     * 
     * @param category
     *            category
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * 获取 page
     * 
     * @return page
     */
    public int getPage() {
        return page;
    }

    /**
     * 
     * 设置page
     * 
     * 
     * @param page
     *            page
     */
    public void setPage(int page) {
        this.page = page;
    }

    /**
     * 获取 author
     * 
     * @return author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * 
     * 设置author
     * 
     * 
     * @param author
     *            author
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * 获取 fullflag
     * 
     * @return fullflag
     */
    public Boolean getFullflag() {
        return fullflag;
    }

    /**
     * 
     * 设置fullflag
     * 
     * 
     * @param fullflag
     *            fullflag
     */
    public void setFullflag(Boolean fullflag) {
        this.fullflag = fullflag;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * 获取 articleList
     * 
     * @return articleList
     */
    public List<TArticle> getArticleList() {
        return articleList;
    }

    /**
     * 
     * 设置articleList
     * 
     * 
     * @param articleList
     *            articleList
     */
    public void setArticleList(List<TArticle> articleList) {
        this.articleList = articleList;
    }

    @Override
    public String getTempName() {
        return "articleList";
    }

    @Override
    protected void loadData() {
        logger.debug("loadData start.");

        ArticleSearchBean searchBean = new ArticleSearchBean();
        BeanUtils.copyProperties(this, searchBean);
        searchBean.setPageType(ArticleSearchBean.PageType.publicPage);

        pagination.setPageNumber(page == 0 ? 1 : page);
        pagination.setSortColumn(TArticle.PROP_LASTUPDATE);
        pagination.setSortOrder("DESC");

        int count = 0;
        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_CACHE_ARTICLE_COUNT, false)) {
            // 开启缓存件数的话
            if (Utils.isDefined(category)) {
                // 分类
                count = ArticleCountManager.getArticleCount(String.valueOf(category));
            } else if (Utils.isDefined(author)) {
                count = ArticleCountManager.getArticleCount(YiDuConstants.CacheCountType.AUTHOR);
            } else if (fullflag != null && fullflag) {
                count = ArticleCountManager.getArticleCount(YiDuConstants.CacheCountType.FULLFLAG);
            } else if (Utils.isDefined(tag)) {
                count = ArticleCountManager.getArticleCount(YiDuConstants.CacheCountType.TAG);
            } else {
                count = ArticleCountManager.getArticleCount(YiDuConstants.CacheCountType.ALL);
            }
        } else {
            Object countInfo = CacheManager.getObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_COUNT_PREFIX,
                    searchBean);
            if (countInfo == null) {
                count = articleService.getCount(searchBean);
                CacheManager.putObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_COUNT_PREFIX, searchBean,
                        count);
            } else {
                count = Integer.parseInt(countInfo.toString());
            }
        }
        // 总件数设置
        pagination.setPreperties(count);
        searchBean.setPagination(pagination);

        articleList = CacheManager.getObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_PREFIX, searchBean);
        if (!Utils.isDefined(articleList)) {
            articleList = articleService.find(searchBean);
            CacheManager.putObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_PREFIX, searchBean, articleList);
        }
        logger.debug("normally end.");
    }

    @Override
    public int getPageType() {
        return YiDuConstants.Pagetype.PAGE_ARTICLE_LIST;
    }

    @Override
    protected String getBlockKey() {
        return CacheManager.CacheKeyPrefix.CACHE_KEY_CATEGORY_LIST_BLOCK;
    }

    @Override
    protected Short getBlockTarget() {
        return YiDuConstants.BlockTarget.ARTICLE_LIST;
    }
}

src/main/java/org/yidu/novel/action/BookcaseAction.java
package org.yidu.novel.action;

import org.yidu.novel.action.base.AbstractPublicBaseAction;
import org.yidu.novel.constant.YiDuConstants;

/**
 * 
 * <p>
 * 书架管理Action
 * </p>
 * Copyright(c) 2013 YiDu-Novel. All rights reserved.
 * 
 * @version 1.0.0
 * @author shinpa.you
 */
public class BookcaseAction extends AbstractPublicBaseAction {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = 366181195078436796L;

    /**
     * 获得模版名字
     * 
     * @return 模版名字
     */
    @Override
    public String getTempName() {
        return "bookcase";
    }

    @Override
    public int getPageType() {
        return YiDuConstants.Pagetype.PAGE_BOOKCASE;
    }

    @Override
    protected void loadData() {
    }
}

src/main/java/org/yidu/novel/action/base/AbstractAdminBaseAction.java
package org.yidu.novel.action.base;

import org.apache.struts2.interceptor.validation.SkipValidation;

import com.opensymphony.xwork2.Action;

/**
 * <p>
 * 管理画面的基类
 * </p>
 * Copyright(c) 2013 YiDu-Novel. All rights reserved.
 * 
 * @version 1.0.0
 * @author shinpa.you
 */
public abstract class AbstractAdminBaseAction extends AbstractBaseAction {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = 4900892616460135567L;
    /**
     * 命名空间。
     */
    public static final String NAMESPACE = "/admin";

    /**
     * 读取数据
     */
    protected abstract void loadData();

    @Override
    @SkipValidation
    public String execute() {
        logger.debug("execute start.");
        initCollections(new String[] { "collectionProperties.article.category" });
        loadData();
        if (this.hasErrors()) {
            logger.debug("execute abnormally end.");
            return ADMIN_ERROR;
        }
        logger.debug("execute normally end.");
        return Action.INPUT;
    }

}

src/main/webapp/themes/default/wap/articleList.ftl
<#include "base.ftl"/>

<#macro titleContent>  
<#if category?? && category!=0 >
<title>${categorymap[category?c]}小说|${getText("label.system.title")}</title>
<meta name="keywords" content="${categorymap[category?c]},${categorymap[category?c]}小说,${getText("label.system.siteKeywords")}" />
<#elseif author?? >
<title>${author}的小说|${getText("label.system.title")}</title>
<meta name="keywords" content="${author}的小说,${getText("label.system.siteKeywords")}" />
<meta name="description" content="${getText("label.system.siteDescription")}" />
<#else>
<title>完本小说|${getText("label.system.title")}</title>
<meta name="keywords" content="完本小说,${getText("label.system.siteKeywords")}" />
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#if>
</#macro>
<#macro content>
    <div class="m10">
        <ul class="cate">
            <li id="categories">
                    <#list categorymap?keys as categorykey>
                    <a href="${encodeURL("/articleList?category=${categorykey}")}" <#if category?? && categorykey==category?c>class="curr"</#if>>${categorymap[categorykey]?substring(0,2)}</a>
                    </#list>
                    <a href="${encodeURL("/articleList?fullflag=true")}" <#if fullflag?? && fullflag>class="curr"</#if>>完本</a>
            </li>
            <li id="books">
            <#list articleList as article>
                <div class="info i3">
                 <a href="${article.url}">
                     <img src="${article.imgUrl}" />
                     <h3>${article.articlename}</h3>
                     <p>作者：${article.author}</p>
                     <p>字数：${article.size?c} (有${article.allvisit?c}人阅读)</p>
                     <#if article.fullflag>
                           <em class="wj3"></em>
                     </#if>
                 </a>
             </div>
             </#list>
            </li>
        </ul>
        <div class="m1">
            <a id="lnkMore" class="loading ww" href="/search">前往搜索页查看更多作品</a>
        </div>
    </div>
</#macro>

src/main/webapp/themes/default/wap/error.ftl
<#include "base.ftl"/>

<#macro titleContent>  
<title>${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}"/>
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>

<#macro top>
    <div class="top">
        <ul>
            <li><a href="${contextPath}/user/center"></a></li>
            <li><a></a></li>
            <li><a href="search.aspx"></a></li>
        </ul>
    </div>
    <div class="search">
        <ul>
            <li><input id="txtKeyword" type="text" data-text="请输入书名/作者名/关键字" value="请输入书名/作者名/关键字" /></li>
            <li><a id="lnkSearch" class="sbtn" href="javascript:;">搜索</a></li>
        </ul>
        <div style="display:none">
            <script type="text/javascript">
                $("#txtKeyword").click(function () {
                    if ($(this).val() == $(this).attr("data-text"))
                        $(this).val("");
                }).blur(function () {
                    if ($(this).val() == "")
                        $(this).val($(this).attr("data-text"));
                });
            </script>
        </div>
    </div>
    <div class="nav m10">
        <ul>
            <li class="curr"><a href="${contextPath}/">首页</a></li>
            <li><a href="${encodeURL("/top")}">排行</a></li>
            <li><a href="${encodeURL("/mobileCategory")}">分类</a></li>
            <li><a href="${encodeURL("/user/bookcase")}">书架</a></li>
        </ul>
    </div>
</#macro>


<#macro content>
<section class="section board-list board-list-collapse">
    <p class="b-all-switch normal">出现错误！</p>
    <div class="msgwin mgl_61" style="text-align:center;">
        <div class="blockcontent">
            <div style="padding:10px"><br />
        <@s.actionerror /><br />请&nbsp;<a href="javascript:history.back(1)">返 回</a>&nbsp;并修正或&nbsp;<a href="${contextPath}/">返回首页</a><br /><br /></div>
        </div>
    </div>
</section>
</#macro>

src/main/webapp/themes/default/wap/index.ftl
<#include "base.ftl"/>

<#macro titleContent>  
<title>${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}"/>
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>

<#macro recommendblock articleList title id style> 
<div class="${style}">
        <div class="title">${title}</div>
        <div id="divChange${id}" class="info m2">
            <#if articleList?? && (articleList?size > 0) >
            <a href="${encodeURL("/info?subdir=${articleList[0].subdir?c}&articleno=${articleList[0].articleno?c}")}">
                <img src="${articleList[0].imgUrl}" />
                <h3>${articleList[0].articlename?html}</h3>
                <p>作者：${articleList[0].author?html}</p>
                <p>${articleList[0].introForHtml}</p>
            </a>
            </#if>
        </div>
        <ul id="ulChange${id}" class="list">
        <#list articleList as article>
            <#if article_index !=0>    
                <li><a href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}">${categorymap[article.category?c]}：${article.articlename?html}</a></li>
            </#if>
        </#list>
        </ul>
</div>
</#macro>


<#macro content>
    <div class="m8">
        <div class="rec">
            <ul>
            <#list blocks.index_hot_list_mobile as article>
                <li><a href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}"><img height="117px" width="91px" src="${article.imgUrl}" /></a></li>
            </#list>
            </ul>
        </div>
    </div>

    <#if recommendblock?exists>
          <@recommendblock articleList=blocks.last_update_list_mobile title="最近更新" id="1" style="m5"/>
    </#if>
    
    <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_yanqing_tuijian title="热门言情" id="2" style="m10"/>
    </#if>
    
     <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_xuanhuan_tuijian title="热门玄幻" id="3" style="m10"/>
    </#if>
    
     <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_junshi_tuijian title="热门军事" id="4" style="m10"/>
    </#if>
    
     <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_kongbu_tuijian title="热门恐怖" id="5" style="m10"/>
    </#if>
    
     <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_wuxia_tuijian title="热门武侠" id="6" style="m10"/>
    </#if>

</#macro> 

src/main/webapp/themes/default/wap/top.ftl
<#include "base.ftl"/>

<#macro titleContent>
<#assign topNameMap = topNameJsonData?eval>
<#assign mobileTopNameMap = mobileTopNameJsonData?eval>
<title>${topNameMap[sortColumn]}|${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}" />
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>

<#macro content>
    <div class="m10">
        <ul class="cate">
            <li id="categories">
                    <#list mobileTopNameMap?keys as topkey>
                    <a href="${encodeURL("/top?sortColumn=${topkey}")}" <#if sortColumn==topkey>class="curr"</#if>>${mobileTopNameMap[topkey]?substring(0,3)}</a>
                    </#list>
            </li>
            <li id="books">
            <#list articleList as article>
                <div class="info i3">
                 <a href="${article.url}">
                     <img src="${article.imgUrl}" />
                     <h3>${article.articlename}</h3>
                     <p>作者：${article.author}</p>
                     <p>类别：${article.categoryStr}</p>
                     <#if article.fullflag>
                           <em class="wj3"></em>
                     </#if>
                 </a>
             </div>
             </#list>
            </li>
        </ul>
        <div class="m1">
            <a id="lnkMore" class="loading ww" href="/search">前往搜索页查看更多作品</a>
        </div>
    </div>
</#macro>